"""
Copyright (c) 2010 cmiVFX.com <info@cmivfx.com>

This file is part of AtomSplitter.

AtomSplitter is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

AtomSplitter is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with AtomSplitter.  If not, see <http://www.gnu.org/licenses/>.

Written by: Justin Israel
			justinisrael@gmail.com
			justinfx.com

"""


class ChanToTerragen(object):
	
	def __init__(self, chanObject, data, scale=1.0):
		self.__chanObject = chanObject
		self.__data = data.copy()
		self.scale = scale
	
	
	def convert(self):
		""" """
		self.__data['keyData'] = self.__chanObject.getKeyData()

		rendered = self.getTemplate(self.__data)
		
		return rendered
		
	
	def getTemplate(self, data):
		""" Returns the .TGD file template """
		
		templateData = {}
		templateData.update(data)
		templateData['cameraData'] = self._getCamera(data)
		
		# main template
		template = """
			<terragen
				name = "Project"
				gui_use_node_pos = "1"
				gui_node_pos = "660 -160 0"
				gui_group = ""
				written_by_program = "Terragen 2"
				written_by_version = "2.1.18.1"
				author = "AtomSplitter"
				comments = "Generated by AtomSplitter (cmivfx.com / justinfx.com)"
				current_frame = "1"
				start_frame = "%(start)s"
				end_frame = "%(finish)s"
				gui_network_view_position = "-122.6151407 260.0007886 0"
				gui_network_view_size = "535 324 0"
				gui_network_view_zoom = "0.1928891417"
				>
				<camera
					name = "Render Camera"
					gui_use_node_pos = "1"
					gui_node_pos = "640 60 0"
					gui_group = "Cameras"
					position = "0 1000 -1300"
					rotation = "-20 30 0"
					light_exposure = "1"
					motion_blur_length = "0.5"
					subject_distance = "100"
					aperture_diameter_in_mm = "5"
					perspective = "1"
					use_horizontal_fov = "1"
					horizontal_fov = "60"
					use_vertical_fov = "0"
					vertical_fov = "40"
					focal_length_in_mm = "31.17691454"
					film_aperture_in_mm = "36 24"
					orthographic = "0"
					use_ortho_width = "1"
					ortho_width = "1000"
					use_ortho_height = "0"
					ortho_height = "1000"
					import_position = "1"
					import_rotation = "1"
					import_Z_up = "0"
					import_vertical_FOV = "1"
					import_focal_length = "0"
					import_focal_length_to_FOV = "0"
					do_not_import_FOV = "0"
					import_offset = "0 0 0"
					import_scale = "1"
					import_filename = ""
					>
				</camera>
				<render
					name = "Full Render"
					gui_use_node_pos = "1"
					gui_node_pos = "960 -120 0"
					gui_group = "Renderers"
					master = "1"
					image_width = "640"
					lock_aspect_ratio = "0"
					image_height = "480"
					image_aspect_ratio = "1.33333"
					pixel_aspect_ratio = "1"
					camera = "Render Camera"
					surfaces_visible = "1"
					atmosphere_visible = "1"
					do_shadows = "1"
					detail = "0.5"
					anti-aliasing = "3"
					ray_trace_objects = "1"
					GI_relative_detail = "2"
					GI_sample_quality = "2"
					GI_blur_radius = "8"
					supersample_prepass = "0"
					GI_surface_details = "0"
					do_crop_region = "0"
					crop_left = "0"
					crop_right = "1"
					crop_bottom = "0"
					crop_top = "1"
					crop_to_object = "0"
					crop_object_name = ""
					pixel_filter = "2"
					anti-aliasing_bloom = "1"
					detail_blending = "0"
					displacement_filter = "1"
					microvertex_jittering = "1"
					detail_jittering = "1"
					lock_subdiv_to_frame = "0"
					lock_to_frame_number = "1"
					do_reverse_primary_rays = "0"
					reverse_primary_rays_multiplier = "1"
					fix_holes = "1"
					do_ray_traced_shadows = "1"
					ray_trace_everything = "0"
					soft_clip_effect = "1"
					soft_clip_softness = "1"
					compensate_soft_clip = "1"
					contrast = "1"
					contrast_adjust = "0.25"
					gamma_correction = "2.2"
					minimum_threads = "1"
					maximum_threads = "16"
					size_of_subdiv_cache_in_Mb = "400"
					preallocate_subdiv_cache = "0"
					ray_detail_region = "1"
					ray_detail_region_padding = "0"
					output_image_filename = "/temp.%%04d.bmp"
					extra_output_images = "1"
					extra_output_image_filename = "/temp.IMAGETYPE.%%04d.bmp"
					micro_exporter = "0"
					micro_exporter_name = ""
					sequence_first = "1"
					sequence_last = "100"
					sequence_step = "1"
					>
				</render>
				<render
					name = "Quick Render"
					gui_use_node_pos = "1"
					gui_node_pos = "960 -180 0"
					gui_group = "Renderers"
					master = "0"
					image_width = "320"
					lock_aspect_ratio = "0"
					image_height = "240"
					image_aspect_ratio = "1.33333"
					pixel_aspect_ratio = "1"
					camera = "Render Camera"
					surfaces_visible = "1"
					atmosphere_visible = "1"
					do_shadows = "1"
					detail = "0.25"
					anti-aliasing = "2"
					ray_trace_objects = "1"
					GI_relative_detail = "2"
					GI_sample_quality = "2"
					GI_blur_radius = "8"
					supersample_prepass = "0"
					GI_surface_details = "0"
					do_crop_region = "0"
					crop_left = "0"
					crop_right = "1"
					crop_bottom = "0"
					crop_top = "1"
					crop_to_object = "0"
					crop_object_name = ""
					pixel_filter = "2"
					anti-aliasing_bloom = "0"
					detail_blending = "0"
					displacement_filter = "1"
					microvertex_jittering = "1"
					detail_jittering = "1"
					lock_subdiv_to_frame = "0"
					lock_to_frame_number = "1"
					do_reverse_primary_rays = "0"
					reverse_primary_rays_multiplier = "1"
					fix_holes = "1"
					do_ray_traced_shadows = "1"
					ray_trace_everything = "0"
					soft_clip_effect = "1"
					soft_clip_softness = "1"
					compensate_soft_clip = "1"
					contrast = "1"
					contrast_adjust = "0.25"
					gamma_correction = "2.2"
					minimum_threads = "1"
					maximum_threads = "16"
					size_of_subdiv_cache_in_Mb = "400"
					preallocate_subdiv_cache = "0"
					ray_detail_region = "1"
					ray_detail_region_padding = "0"
					output_image_filename = "/temp.%%04d.bmp"
					extra_output_images = "1"
					extra_output_image_filename = "/temp.IMAGETYPE.%%04d.bmp"
					micro_exporter = "0"
					micro_exporter_name = ""
					sequence_first = "1"
					sequence_last = "100"
					sequence_step = "1"
					>
				</render>
				<enviro_light
					name = "Enviro light"
					gui_use_node_pos = "1"
					gui_node_pos = "320 0 0"
					gui_group = "Lighting"
					enable = "1"
					mode = "1"
					ambient_strength_on_surfaces = "1"
					ambient_colour_on_surfaces = "0.6499999762 0.8000000119 1"
					ambient_strength_in_atmosphere = "1"
					ambient_colour_in_atmosphere = "0.6499999762 0.8000000119 1"
					global_strength_on_surfaces = "1"
					global_tint_on_surfaces = "1 1 1"
					global_strength_in_atmosphere = "1"
					global_tint_in_atmosphere = "1 1 1"
					strength_on_surfaces = "1"
					colour_on_surfaces = "1 1 1"
					strength_in_atmosphere = "1"
					colour_in_atmosphere = "1 1 1"
					>
				</enviro_light>
				<sunlight
					name = "Sunlight 01"
					gui_use_node_pos = "1"
					gui_node_pos = "320 -60 0"
					gui_group = "Lighting"
					enable = "1"
					heading = "300"
					elevation = "25"
					colour = "1 1 1"
					strength = "3.5"
					cast_shadows = "1"
					shadows_of_surfaces = "1"
					shadows_of_atmosphere = "1"
					soft_shadows_separator = "Soft Shadows"
					soft_shadows = "0"
					soft_shadow_diameter = "0.5"
					soft_shadow_samples = "9"
					glow_in_atmosphere = "1"
					specular_highlights = "1"
					sun_disc_separator = "Sun Disc"
					visible_disc = "1"
					angular_diameter = "0.5"
					>
				</sunlight>
				<sphere
					name = "Background"
					gui_use_node_pos = "1"
					gui_node_pos = "0 -60 0"
					gui_group = "Objects"
					enable = "1"
					show_b-box_in_preview = "0"
					visible_to_camera = "1"
					visible_to_other_rays = "1"
					cast_shadows = "0"
					centre = "0 0 0"
					radius = "-200000000"
					rotate = "0 0 0"
					import_motion_filename = ""
					heading = "0"
					elevation = "0"
					distance = "0"
					surface_shader = "Background shader"
					displacement_tolerance = "1"
					>
					<constant_shader
						name = "Background shader"
						gui_use_node_pos = "1"
						gui_node_pos = "200 0 0"
						gui_group = ""
						enable = "1"
						input_node = ""
						gui_use_preview_patch_size = "0"
						gui_preview_patch_size = "1000 1000"
						colour = "0 0 0"
						alpha = "0 0 0"
						>
					</constant_shader>
				</sphere>
				<planet
					name = "Planet 01"
					gui_use_node_pos = "1"
					gui_node_pos = "0 0 0"
					gui_group = "Objects"
					enable = "1"
					show_b-box_in_preview = "0"
					render_surface = "1"
					render_atmosphere = "1"
					lat_long_at_apex = "0 0"
					centre = "0 -6378000 0"
					radius = "6378000"
					rotate = "0 0 0"
					import_motion_filename = ""
					heading = "0"
					elevation = "270"
					distance = "6378000"
					surface_shader = "Base colours"
					atmosphere_shader = "Atmosphere 01"
					displacement_tolerance = "1"
					>
				</planet>
				<planet_atmosphere
					name = "Atmosphere 01"
					gui_use_node_pos = "1"
					gui_node_pos = "0 220 0"
					gui_group = "Atmosphere"
					enable = "1"
					input_node = ""
					gui_use_preview_patch_size = "0"
					gui_preview_patch_size = "1000 1000"
					enable_primary = "1"
					enable_secondary = "1"
					centre = "0 -6378000 0"
					radius = "6378000"
					seed = "0"
					haze_density = "1.5"
					haze_horizon_colour = "0.349999994 0.349999994 0.349999994"
					bluesky_density = "2"
					bluesky_horizon_colour = "0.224999994 0.3585940003 0.4499999881"
					bluesky_additive = "0.9"
					bluesky_additive_colour = "0.05000000075 0.270938009 1"
					redsky_decay = "2"
					haze_exp_height = "3000"
					bluesky_exp_height = "8000"
					ceiling_adjust = "7"
					ceiling = "56000"
					floor = "-16000"
					haze_glow_amount = "1"
					haze_glow_power = "1.25"
					bluesky_glow_amount = "0.25"
					bluesky_glow_power = "0.75"
					enviro_light = "0.5"
					enviro_light_tint = "1 1 1"
					ambient = "0 0 0"
					fake_dark_power = "0"
					fake_dark_sharpness = "10"
					bluesky_density_colour = "0.1000000015 0.3400000036 1"
					redsky_decay_colour = "0.9048374295 0.7117702961 0.3678794503"
					improved_glow_model = "1"
					number_of_samples = "16"
					adjust_to_distance = "1"
					sample_jitter = "1"
					enable_ray_traced_shadows = "0"
					ray_traced_shadows_warning_0 = "Enable ray traced shadows only if you need terrains and other surfaces to cast"
					ray_traced_shadows_warning_1 = "visible shadows in atmosphere or to hide lightsource glows behind surfaces."
					>
				</planet_atmosphere>
				<power_fractal_shader_v3
					name = "Base colours"
					gui_use_node_pos = "1"
					gui_node_pos = "-920 220 0"
					gui_group = "Shaders"
					enable = "1"
					input_node = "Compute Terrain"
					gui_use_preview_patch_size = "0"
					gui_preview_patch_size = "1000 1000"
					seed = "8028"
					feature_scale = "1"
					lead-in_scale = "1000"
					smallest_scale = "0.1"
					noise_octaves = "15"
					apply_high_colour = "1"
					high_colour = "0.3000000119 0.3000000119 0.3000000119"
					apply_low_colour = "1"
					low_colour = "0 0 0"
					colour_contrast = "0.125"
					colour_offset = "0"
					colour_roughness = "5"
					clamp_high_colour = "1"
					clamp_low_colour = "1"
					apply_displacement = "0"
					displacement_direction = "1"
					displacement_amplitude = "1"
					displacement_offset = "0"
					displacement_roughness = "1"
					displacement_spike_limit = "1"
					continue_spike_limit = "0"
					adjust_coastline = "0"
					coastline_altitude = "0"
					coastline_smoothing = "30"
					noise_flavour = "0"
					noise_variation = "1"
					variation_method = "2"
					buoyancy_from_variation = "0"
					clumping_of_variation = "0"
					noise_stretch_XYZ = "1 1 1"
					distort_by_normal = "1"
					distortion_by_normal = "5"
					lead-in_warp_effect = "1"
					lead-in_warp_amount = "0.5"
					less_warp_at_feature_scale = "0"
					allow_vertical_warp = "0"
					blend_by_shader = "0"
					blending_shader = ""
					fit_blendshader_to_this = "0"
					invert_blendshader = "0"
					>
				</power_fractal_shader_v3>
				<heightfield_shader
					name = "Heightfield shader 01"
					gui_use_node_pos = "1"
					gui_node_pos = "-920 600 0"
					gui_group = "Terrain"
					enable = "1"
					input_node = ""
					gui_use_preview_patch_size = "0"
					gui_preview_patch_size = "1000 1000"
					heightfield = "Heightfield generate 01"
					flip_x = "0"
					flip_y = "0"
					position_centre = "0"
					position_lower_left = "1"
					position_upper_left = "0"
					position = "0 0"
					apply_colour_and_shade = "0"
					diffuse_colour = "1 1 1"
					ambient_light_colour = "0 0 0"
					shade_by_light = "1"
					shade_by_height = "0"
					height_multiplier = "1"
					flatten_surface_first = "1"
					interpolation_method = "3"
					add_fractal_detail = "1"
					fractal_amount = "0.5"
					fractal_scale_adjust = "4"
					fractal_variation = "1.5"
					fractal_roughness = "1"
					fractal_flow_factor = "0"
					border_blending = "0.1"
					blend_by_heightfield = "0"
					blending_heightfield = ""
					blend_by_shader = "0"
					blending_shader = ""
					fit_blendshader_to_this = "1"
					invert_blendshader = "0"
					>
				</heightfield_shader>
				<heightfield_generate
					name = "Heightfield generate 01"
					gui_use_node_pos = "1"
					gui_node_pos = "-720 660 0"
					gui_group = "Terrain"
					input_node = ""
					new_heightfield = "1"
					size_in_pixels = "1000 1000"
					size_in_metres = "10000 10000"
					feature_scale = "2000"
					feature_steepness = "0.25"
					roughness = "0.875"
					seed = "22328"
					variation = "1.5"
					variation_method = "2"
					buoyancy_from_variation = "0.5"
					shader = ""
					position_center = "0"
					position_lower_left = "1"
					position = "0 0"
					auto_generate = "0"
					>
				</heightfield_generate>
				<compute_terrain
					name = "Compute Terrain"
					gui_use_node_pos = "1"
					gui_node_pos = "-920 500 0"
					gui_group = "Terrain"
					enable = "1"
					input_node = "Heightfield shader 01"
					gui_use_preview_patch_size = "0"
					gui_preview_patch_size = "1000 1000"
					gradient_patch_size = "20"
					smooth_surface = "0"
					>
				</compute_terrain>
				<group
					name = "Objects"
					gui_use_node_pos = "1"
					gui_node_pos = "0 -80 0"
					gui_group = ""
					gui_node_size = "240 320 1"
					gui_node_colour = "0.8000000119 0.8000000119 0.8000000119"
					special_group = "1"
					global_bookmark = "1"
					>
				</group>
				<group
					name = "Terrain"
					gui_use_node_pos = "1"
					gui_node_pos = "-720 600 0"
					gui_group = ""
					gui_node_size = "640 320 1"
					gui_node_colour = "0.2119999975 0.5174000263 0.1138999984"
					special_group = "2"
					global_bookmark = "1"
					>
				</group>
				<group
					name = "Shaders"
					gui_use_node_pos = "1"
					gui_node_pos = "-720 220 0"
					gui_group = ""
					gui_node_size = "640 280 1"
					gui_node_colour = "0.7968999743 0.1604000032 0.1604000032"
					special_group = "3"
					global_bookmark = "1"
					>
				</group>
				<group
					name = "Water"
					gui_use_node_pos = "1"
					gui_node_pos = "200 600 0"
					gui_group = ""
					gui_node_size = "640 240 1"
					gui_node_colour = "0.1000000015 0.5 0.349999994"
					special_group = "4"
					global_bookmark = "1"
					>
				</group>
				<group
					name = "Atmosphere"
					gui_use_node_pos = "1"
					gui_node_pos = "200 230 0"
					gui_group = ""
					gui_node_size = "640 160 1"
					gui_node_colour = "0.2310000062 0.3203999996 1"
					special_group = "5"
					global_bookmark = "1"
					>
				</group>
				<group
					name = "Lighting"
					gui_use_node_pos = "1"
					gui_node_pos = "320 -80 0"
					gui_group = ""
					gui_node_size = "240 320 1"
					gui_node_colour = "1 0.7299000025 0.2195000052"
					special_group = "6"
					global_bookmark = "1"
					>
				</group>
				<group
					name = "Cameras"
					gui_use_node_pos = "1"
					gui_node_pos = "640 -80 0"
					gui_group = ""
					gui_node_size = "240 320 1"
					gui_node_colour = "0.3021000028 0.2673999965 0.4647000134"
					special_group = "7"
					global_bookmark = "1"
					>
				</group>
				<group
					name = "Renderers"
					gui_use_node_pos = "1"
					gui_node_pos = "973 -80 0"
					gui_group = ""
					gui_node_size = "266.0336416 320 1"
					gui_node_colour = "0.7372000217 0.3440000117 0.2119999975"
					special_group = "8"
					global_bookmark = "1"
					>
				</group>
				%(cameraData)s
			</terragen>
	
		"""
		template = template.replace('\n\t\t\t', '\n').lstrip()
		
		return template % templateData
	
	def _getCamera(self, data):
		
		data['animData'] = self._getAnimData(data)
		
		template = """
			<camera
				name = "Camera 01"
				gui_use_node_pos = "1"
				gui_node_pos = "640 0 0"
				gui_group = "Cameras"
				position = "0 2 -10"
				rotation = "0 0 0"
				light_exposure = "1"
				motion_blur_length = "0.5"
				subject_distance = "100"
				aperture_diameter_in_mm = "5"
				perspective = "1"
				use_horizontal_fov = "0"
				horizontal_fov = "%(fov)0.3f"
				use_vertical_fov = "1"
				vertical_fov = "%(fov)0.3f"
				focal_length_in_mm = "%(focalLength)0.3f"
				film_aperture_in_mm = "%(filmWidth)0.3f %(filmHeight)0.3f"
				orthographic = "0"
				use_ortho_width = "1"
				ortho_width = "1000"
				use_ortho_height = "0"
				ortho_height = "1000"
				import_position = "0"
				import_rotation = "0"
				import_Z_up = "0"
				import_vertical_FOV = "1"
				import_focal_length = "0"
				import_focal_length_to_FOV = "0"
				do_not_import_FOV = "0"
				import_offset = "0 0 0"
				import_scale = "1"
				import_filename = ""
				>
				%(animData)s
			</camera>
		"""
		template = template.replace('\n\t\t', '\n').lstrip()	
		
		return template % data
	
	def _getAnimData(self, data):
		
		posData = []
		rotData = []
		fovData = []
		
		posStr = rotStr = fovStr = ''
		
		keyData = data['keyData']
		keys = keyData.keys()
		scale = self.scale
		
		for frame in sorted(keys):
			attribs = keyData[frame]
			
			x,y,z = attribs['tx'], attribs['ty'], attribs['tz']
			posData.append('vf%s = "%s %s %s"' % (frame, x*scale, y*scale, z*scale*-1.0))

			x,y,z = attribs['rx'], attribs['ry'], attribs['rz']
			rotData.append('vf%s = "%s %s %s"' % (frame, x, y*-1.0, z*-1.0))
			
			fovData.append('vf%s = "%s"' % (frame, attribs['fov']))
		
		
		if posData:
			posData.insert(0, '<param name = "position"')
			posData.append('/>')
			posStr = '\n\t\t\t'.join( posData )

		if rotData:
			rotData.insert(0, '\t\t<param name = "rotation"')
			rotData.append('/>')
			rotStr = '\n\t\t\t'.join( rotData )

		if fovData:
			fovData.insert(0, '\t\t<param name = "vertical_fov"')
			fovData.append('/>')
			fovStr = '\n\t\t\t'.join( fovData )
		
		animData = '\n'.join( (posStr, rotStr, fovStr) ).strip('\n')
		return animData

		
